"""add pricing models

Revision ID: 463aa5c25f3c
Revises: ea92e5ebd9ef
Create Date: 2026-06-06 19:10:21.445442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463aa5c25f3c'
down_revision: Union[str, Sequence[str], None] = 'ea92e5ebd9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('denomination_id', sa.Integer(), nullable=False),
    sa.Column('base_buy_rate', sa.Float(), nullable=False),
    sa.Column('sell_markup_pct', sa.Float(), nullable=False),
    sa.Column('min_rate', sa.Float(), nullable=False),
    sa.Column('max_rate', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['card_brands.id'], ),
    sa.ForeignKeyConstraint(['denomination_id'], ['denominations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('denomination_id', sa.Integer(), nullable=False),
    sa.Column('effective_buy_rate', sa.Float(), nullable=False),
    sa.Column('effective_sell_price', sa.Float(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['card_brands.id'], ),
    sa.ForeignKeyConstraint(['denomination_id'], ['denominations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.Enum('STOCK_LOW', 'STOCK_HIGH', 'SUBMISSION_VOLUME_HIGH', 'DAY_OF_WEEK', name='triggertype'), nullable=False),
    sa.Column('operator', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('adjustment_pct', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rate_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_adjustments')
    op.drop_table('rate_snapshots')
    op.drop_table('rate_rules')
    # ### end Alembic commands ###
