"""add orders table

Revision ID: dffad776099d
Revises: 81df7b96d5a9
Create Date: 2026-06-06 19:40:14.398256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dffad776099d'
down_revision: Union[str, Sequence[str], None] = '81df7b96d5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('reloadly_tx_id', sa.String(length=255), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'REFUNDED', 'FAILED', name='orderstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('PAYSTACK', 'FLUTTERWAVE', 'BANK_TRANSFER', 'MOBILE_MONEY', 'CRYPTO', name='paymentmethod'), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
